import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import importPlugin from 'eslint-plugin-import';
import jestPlugin from 'eslint-plugin-jest';
import prettierPlugin from 'eslint-plugin-prettier';
import prettierConfig from 'eslint-config-prettier';
import eslintComments from 'eslint-plugin-eslint-comments';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const tsconfigRootDir = dirname(fileURLToPath(import.meta.url));

const sharedRules = {
  ...prettierConfig.rules,
  ...eslintComments.configs.recommended.rules,
  'class-methods-use-this': 'off',
  'prefer-destructuring': 'off',
  'sort-keys': 'off',
  'no-unused-vars': 'off',
  'max-statements': 'off',
  'arrow-parens': 'off',
  indent: 'off',
  'comma-dangle': 'off',
  'max-lines-per-function': 'off',
  'no-underscore-dangle': 'off',
  'arrow-body-style': 'off',
  'no-magic-numbers': 'off',
  'prefer-const': 'off',
  'padded-blocks': 'off',
  'eol-last': 'off',
  semi: 'off',
  'import/order': 'off',
  'import/newline-after-import': 'off',
  'max-len': 'off',
  'no-multiple-empty-lines': 'off',
  'array-element-newline': 'off',
  'line-comment-position': 'off',
  'no-inline-comments': 'off',
  'func-style': 'off',
  'spaced-comment': 'off',
  'multiline-comment-style': 'off',
  'lines-around-comment': 'off',
  'no-ternary': 'off',
  'no-restricted-syntax': 'off',
  quotes: 'off',
  'prefer-template': 'off',
  'no-plusplus': 'off',
  'max-params': 'off',
  'consistent-return': 'off',
  'require-await': 'off',
  'no-warning-comments': 'off',
  'quote-props': 'off',
  'require-unicode-regexp': 'off',
  'dot-notation': 'off',
  'object-curly-spacing': 'off',
  'object-curly-newline': 'off',
  'function-paren-newline': 'off',
  'no-promise-executor-return': 'off',
  'multiline-ternary': 'off',
  'no-negated-condition': 'off',
  'no-restricted-globals': 'off',
  'newline-per-chained-call': 'off',
  'no-undefined': 'off',
  'no-trailing-spaces': 'off',
  'one-var': 'off',
  'function-call-argument-newline': 'off',
  'object-property-newline': 'off',
  complexity: 'off',
  'capitalized-comments': 'off',
  'no-implicit-globals': 'off',
  'sort-vars': 'off',
  'guard-for-in': 'off',
  'no-prototype-builtins': 'off',
  'no-confusing-arrow': 'off',
  'no-await-in-loop': 'off',
  strict: 'off',
  'array-bracket-newline': 'off',
  'operator-linebreak': 'off',
  'new-cap': 'off',
  'func-names': 'off',
  'implicit-arrow-linebreak': 'off',
  'no-bitwise': 'off',
  'max-lines': 'off',
  'max-classes-per-file': 'off',
  'prefer-named-capture-group': 'off',
  'no-useless-constructor': 'off',
  eqeqeq: 'off',
  'default-param-last': 'off',
  'space-before-blocks': 'off',
  'no-continue': 'off',
  'prefer-arrow-callback': 'off',
  'no-multi-spaces': 'off',
  'require-atomic-updates': 'off',
  'prefer-object-has-own': 'off',
  radix: 'off',
  'no-extra-parens': 'off',
  'init-declarations': 'off',
  'dot-location': 'off',
  'accessor-pairs': 'off',
  'wrap-regex': 'off',
  'space-before-function-paren': 'off',
  'no-unreachable-loop': 'off',
  'no-use-before-define': 'off',
  'no-mixed-operators': 'off',
  'no-empty': 'off',
  'no-shadow': 'off',
  'no-constant-condition': 'off',
  'no-case-declarations': 'off',
  'id-length': 'off',
  'no-unused-expressions': 'warn',
  'prefer-rest-params': 'warn',
  'no-invalid-this': 'warn',
  'no-useless-catch': 'warn',
  'no-empty-function': 'warn',
  'object-shorthand': 'warn',
  'no-path-concat': 'warn',
  'no-console': 'warn',
  'no-else-return': 'warn',
  camelcase: 'warn',
  'prefer-object-spread': 'warn',
  'no-param-reassign': 'warn',
  'no-implicit-coercion': 'warn',
  'consistent-this': 'warn',
  'no-async-promise-executor': 'warn',
  'no-eq-null': 'warn',
  'key-spacing': 'warn',
  'semi-style': 'warn',
  'default-case': 'warn',
  'arrow-spacing': 'warn',
  'generator-star-spacing': 'warn',
  'prefer-exponentiation-operator': 'warn',
  'no-extra-semi': 'warn',
  'no-unsafe-finally': 'warn',
  'prettier/prettier': 'error',
  '@typescript-eslint/no-var-requires': 'off',
  '@typescript-eslint/no-empty-function': 'off',
  '@typescript-eslint/no-unsafe-return': 'off',
  '@typescript-eslint/no-unsafe-call': 'off',
  '@typescript-eslint/no-unsafe-member-access': 'off',
  '@typescript-eslint/restrict-template-expressions': 'off',
  '@typescript-eslint/no-unsafe-assignment': 'off',
  '@typescript-eslint/no-unsafe-argument': 'off',
  '@typescript-eslint/restrict-plus-operands': 'off',
  '@typescript-eslint/require-await': 'off',
  '@typescript-eslint/no-non-null-assertion': 'off',
  '@typescript-eslint/no-misused-promises': 'off',
  '@typescript-eslint/unbound-method': 'off',
  '@typescript-eslint/no-this-alias': 'off',
  '@typescript-eslint/no-floating-promises': 'off',
  '@typescript-eslint/explicit-module-boundary-types': 'off',
  '@typescript-eslint/no-explicit-any': 'off',
  '@typescript-eslint/no-unnecessary-type-constraint': 'off',
  '@typescript-eslint/no-redundant-type-constituents': 'off',
  '@typescript-eslint/no-unnecessary-type-assertion': 'off',
  '@typescript-eslint/no-unsafe-enum-comparison': 'off',
  '@typescript-eslint/no-unused-vars': [
    'error',
    {
      args: 'none',
      ignoreRestSiblings: true,
    },
  ],
  'jest/no-focused-tests': 'error',
  'jest/no-disabled-tests': 'warn',
  'jest/prefer-to-have-length': 'warn',
  'jest/no-identical-title': 'error',
  'jest/valid-expect': 'error',
};

export default [
  {
    ignores: ['build/**', 'node_modules/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  importPlugin.flatConfigs.typescript,
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir,
        sourceType: 'module',
        ecmaVersion: 2021,
      },
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      jest: jestPlugin,
      prettier: prettierPlugin,
      'eslint-comments': eslintComments,
    },
    rules: sharedRules,
  },
  {
    files: ['tests/**/*.ts'],
    languageOptions: {
      globals: {
        ...jestPlugin.configs['flat/recommended'].languageOptions.globals,
      },
    },
  },
  {
    files: ['test-cli-app/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },
];
